### ISSUE TITLE
Which version Unity and URP is required？

### ISSUE THREAD

**Issue by galaxy-wolf** [ninlilizi/NKLI-AMD-FSR-for-Unity#1]
Hi, I have tried this in Unity 2021.2.0b3  URP 12.0.  it does not work well.
in BeforeEverythingPass function Execute:
                **renderingData.cameraData.targetTexture = RT_FSR_RenderTarget;**
this set a small rendertarget for camera, but it seems not work.
In RenderDoc capture, the render target is still native size.

**Comment by ninlilizi** [comment]
Yes, I've since realized this is happening myself. 

Right now, I've yet to figure out a way to fix that. URP makes everything 100x harder than doing the same thing on the built-in pipeline. So while that's very easy to solve in the built-in pipeline, (and I already have a week ago) URP presents a labyrinth while wearing a blindfold. I'm poking around, but there's zero documentation or any kind of information how URP works, so I'm poking in the dark. If I cannot find a solution eventually, I'll most likely nuke the URP support, as it's just not worth supporting.

**Comment by ninlilizi** [comment]
AMD have now provided their own version for URP here https://gpuopen.com/unity/

As such, I'm nixing my failed attempt at supporting URP, and closing this issue.
